# Generated by Django 3.0.5 on 2020-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followed_open_id',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_open_id',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
