# Generated by Django 3.0.5 on 2020-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='latitude',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='gym',
            name='longitude',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
