# Generated by Django 3.0.5 on 2020-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='brief_introduction',
            field=models.CharField(default='', max_length=225),
        ),
    ]
