# Generated by Django 3.0.5 on 2020-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0006_gym_brief_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favor_sports',
            field=models.CharField(default='', max_length=255),
        ),
    ]
