# Generated by Django 3.0.5 on 2020-04-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0006_gym_brief_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favor_sports',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='responder',
            name='invitation_id_invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='function.Invitation'),
        ),
    ]
