# Generated by Django 3.0.5 on 2020-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0007_auto_20200422_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='inviter_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
