# Generated by Django 3.0.5 on 2020-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0008_auto_20200422_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
