# Generated by Django 3.0.5 on 2020-04-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0009_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='count_invitation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='count_responder',
            field=models.IntegerField(default=0),
        ),
    ]
