# Generated by Django 3.0.5 on 2020-04-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0010_auto_20200430_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
