# Generated by Django 3.0.5 on 2020-05-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0012_message_invitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(default=0),
        ),
    ]
