# Generated by Django 3.0.5 on 2020-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0013_auto_20200503_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(default='', max_length=255),
        ),
    ]
